pipeline {
  agent any

  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }

    stage('Build Image') {
      steps {
        sh 'docker build -t myapp .'
      }
    }

    stage('Deploy') {
      steps {
        sh 'docker run -d -p 3000:3000 myapp'
      }
    }
  }
}
