pipeline {
    agent any

    stages {

        stage('Test') {
            steps {
                sh 'node --version'
            }
        }

        stage('Debug') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

      stage('Build Image') {
    steps {
        sh 'docker build -t myapp my-first-pipeline/'
    }
}

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
